version: '3'
networks:
  loki:
services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    volumes:
      - ./grafana-loki-syslog/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - protocol: tcp
        published: 3100
        target: 3100
    restart: always
    networks:
      - loki
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - ./grafana-loki-syslog/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    ports:
      - protocol: tcp
        published: 1514
        target: 1514
      - protocol: tcp
        published: 9080
        target: 9080
    restart: always
    networks:
      - loki
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "0:0"
    volumes:
    - ./grafana-loki-syslog/grafana:/var/lib/grafana
    ports:
      - protocol: tcp
        published: 3000
        target: 3000
    restart: always
    networks:
      - loki     
  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    volumes:
    - ./grafana-loki-syslog/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    - /home/ivan/syslog-ng/logs:/var/log
    networks:
      - loki
    ports:
    - protocol: udp
      published: 514
      target: 514
    restart: always